### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by okoetter** [mark-hahn/command-toolbar#4]
[Enter steps to reproduce below:]

1. Add settings-view:open to the pane
2. Click on it.

**Atom Version**: 0.176.0
**System**: TSBIEL3000
**Thrown From**: [command-toolbar](https://github.com/mark-hahn/command-toolbar) package, v1.0.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/ko110063/.atom/packages/command-toolbar/lib/toolbar-view.coffee:300

TypeError: undefined is not a function
  at ToolbarView.module.exports.ToolbarView.executeCmd (c:\Users\ko110063\.atom\packages\command-toolbar\lib\toolbar-view.coffee:165:7)
  at ToolbarView.module.exports.ToolbarView.btnClick (c:\Users\ko110063\.atom\packages\command-toolbar\lib\toolbar-view.coffee:174:6)
  at space-pen-div.<anonymous> (c:\Users\ko110063\.atom\packages\command-toolbar\lib\toolbar-view.coffee:286:57)
  at space-pen-div.jQuery.event.dispatch (c:\Users\ko110063\.atom\packages\command-toolbar\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4676:9)
  at space-pen-div.elemData.handle (c:\Users\ko110063\.atom\packages\command-toolbar\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4360:46)

```

### Commands

```
     -1:12.9 core:paste (atom-text-editor.editor.is-focused)
     -1:06.3 core:move-to-top (atom-text-editor.editor.is-focused)
     -1:00.4 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "colorpicker",
      "remember-session",
      "wrap-guide",
      "editorconfig"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "command-toolbar": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.3
color-picker, v1.4.4
command-toolbar, v1.0.3
css-color-underline, v0.1.1
emmet, v2.3.2
git-plus, v4.3.6
highlight-selected, v0.7.0
language-csharp, v0.3.0
language-ini, v1.3.0
monokai, v0.12.0
open-recent, v2.2.0
save-session, v0.11.3
tab-history, v0.4.0
view-tail-large-files, v0.1.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by mark-hahn** [comment]
Thanks for the report.  I couldn't repeat the problem but I cleaned up that area of code and published it as 1.0.4.  Can you please try it again?

**Comment by okoetter** [comment]
I've had this problems for some days now. The interesting part is that as soon as I submitted this report it suddenly began to work again with 1.0.3. Unsurprisingly 1.0.4 also works :-(
Sorry for not having more information...

**Comment by mark-hahn** [comment]
That was plenty of information.  Thanks again.
