### ISSUE TITLE
Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

### ISSUE THREAD

**Issue by okoetter** [mark-hahn/command-toolbar#5]
I have three buttons on my toolbar, this morning none works. 
I found out that it works when I open a new tab via Ctrl-N, but if no tab is open I get this exeption:

C:\Users\ko110063\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:227
Hide Stack Trace
TypeError: Cannot read property 'webkitMatchesSelector' of undefined
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ko110063\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:227:26)
  at CommandRegistry.handleCommandEvent (C:\Users\ko110063\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\ko110063\AppData\Local\atom\app-0.177.0\resources\app\src\command-registry.js:156:19)
  at ToolbarView.module.exports.ToolbarView.executeCmd (C:\Users\ko110063\.atom\packages\command-toolbar\lib\toolbar-view.coffee:161:21)
  at ToolbarView.module.exports.ToolbarView.btnClick (C:\Users\ko110063\.atom\packages\command-toolbar\lib\toolbar-view.coffee:166:6)
  at space-pen-div.<anonymous> (C:\Users\ko110063\.atom\packages\command-toolbar\lib\toolbar-view.coffee:278:57)
  at space-pen-div.jQuery.event.dispatch (C:\Users\ko110063\AppData\Local\atom\app-0.177.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at space-pen-div.elemData.handle (C:\Users\ko110063\AppData\Local\atom\app-0.177.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)

The error was thrown from the command-toolbar package.
Create issue on the command-toolbar package

**Comment by mark-hahn** [comment]
Thanks for the report.

Fixed in 1.0.5.
